---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: deb8
    box: debian/jessie64
    memory: 512
    cpus: 1
    provider_override_args:
      - "ssh.insert_key = false"
      - "vm.synced_folder './', 'vagrant', disabled: true"
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true

  - name: deb9
    box: debian/stretch64
    memory: 512
    cpus: 1
    provider_override_args:
      - "ssh.insert_key = false"
      - "vm.synced_folder './', 'vagrant', disabled: true"
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true

  - name: deb10
    box: debian/buster64
    memory: 512
    cpus: 1
    provider_override_args:
      - "ssh.insert_key = false"
      - "vm.synced_folder './', 'vagrant', disabled: true"
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true

  - name: ubu14
    box: bento/ubuntu-14.04
    memory: 512
    cpus: 1
    provider_override_args:
      - "ssh.insert_key = false"
      - "vm.synced_folder './', 'vagrant', disabled: true"
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true

  - name: ubu16
    box: ubuntu/xenial64
    memory: 512
    cpus: 1
    provider_override_args:
      - "ssh.insert_key = false"
      - "vm.synced_folder './', 'vagrant', disabled: true"
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true

  - name: ubu18
    box: ubuntu/bionic64
    memory: 512
    cpus: 1
    provider_override_args:
      - "ssh.insert_key = false"
      - "vm.synced_folder './', 'vagrant', disabled: true"
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true

  - name: ubu20
    box: bento/ubuntu-20.04
    memory: 512
    cpus: 1
    provider_override_args:
      - "ssh.insert_key = false"
      - "vm.synced_folder './', 'vagrant', disabled: true"
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true

provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
