---
- name: Get SSH version.
  shell:
    'apt-cache policy openssh-server | grep Installed'
  register: ssh_version
  changed_when: False

# If the package's major version is less than 7, use without-password instead of prohibit-password.
- name: Set correct SSH PermitRootLogin value for old SSH versions.
  set_fact:
    ssh_prohibit_password_override: 'without-password'
  when: ssh_version.stdout is regex('1:[0-6]\.')

# Disable password authentication for all users. Forces everyone to use SSH keys.
- name: Disable SSH password authentication.
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "{{ item.regexp }}"
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
    backup: yes
    validate: '/usr/sbin/sshd -t -f %s'
  with_items:
    - regexp: '^PasswordAuthentication '
      insertafter: '^#PasswordAuthentication '
      line: 'PasswordAuthentication no'
    - regexp: '^PermitRootLogin '
      insertafter: '^#PermitRootLogin '
      line: "PermitRootLogin {{ ssh_prohibit_password_override | default('prohibit-password') }}"
  notify: restart ssh

- name: Install basic software.
  apt:
    pkg:
      - tmux
      - vim
      - rsync
    update_cache: yes
    cache_valid_time: 3600

